-- File: seven_segment_decoder.vhd
-- Generated by MyHDL 0.11.52
-- Date:    Sun Oct  4 22:12:33 2026 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity seven_segment_decoder is
    port (
        din: in unsigned(3 downto 0);
        sseg: out unsigned(6 downto 0)
    );
end entity seven_segment_decoder;


architecture MyHDL of seven_segment_decoder is




begin




logic: process (din) is
begin
    case to_integer(din) is
        when 0 => sseg <= "1111110";
        when 1 => sseg <= "0110000";
        when 2 => sseg <= "1101101";
        when 3 => sseg <= "1111001";
        when 4 => sseg <= "0110011";
        when 5 => sseg <= "1011011";
        when 6 => sseg <= "1011111";
        when 7 => sseg <= "1110000";
        when 8 => sseg <= "1111111";
        when 9 => sseg <= "1111011";
        when 10 => sseg <= "1101111";
        when 11 => sseg <= "1001000";
        when 12 => sseg <= "1001110";
        when 13 => sseg <= "1111000";
        when 14 => sseg <= "0001110";
        when others => sseg <= "0001001";
    end case;
end process logic;

end architecture MyHDL;
